[OPS-1109] Pegasus cluster
serokell/pegasus-infra pull request #1
Opened 2020-11-18 15:10 UTC by mkaito

Currently only one server: Helvetios (serokell.io production)

2020-11-18 15:16 UTC, balsoft commented on servers/helvetios/website.nix
> +  services.nginx.virtualHosts.www = {
Does this work without `serverName`?

2020-11-18 15:16 UTC, balsoft commented on terraform/README.md
> +# Terraform files for Aquarius
:pled:

2020-11-18 15:17 UTC, mkaito commented on terraform/README.md
> +# Terraform files for Aquarius
:see_no_evil:

2020-11-18 15:18 UTC, balsoft commented on flake.lock
> +        "url": "file:///home/chris/dev/serokell/serokell.nix"
:roll_eyes:

2020-11-18 15:19 UTC, mkaito commented on servers/helvetios/website.nix
> +  services.nginx.virtualHosts.www = {
Added `default = true;` so the hostname shouldn't matter.

2020-11-18 15:19 UTC, mkaito commented on flake.lock
> +        "url": "file:///home/chris/dev/serokell/serokell.nix"
Yeah, fixed

2020-11-18 15:22 UTC, balsoft commented on flake.nix
> +      terraformFor = pkgs: pkgs.terraform.withPlugins (p: with p; [ aws ]);
I don't really like this, maybe we should just do `pkgs = nixpkgs.legacyPackages.${system}` and then `terraform = pkgs.terraform.withPlugins ...`

2020-11-18 19:22 UTC, mkaito commented on flake.nix
> +      terraformFor = pkgs: pkgs.terraform.withPlugins (p: with p; [ aws ]);
90% of this file is identical to the one in `aquarius-infra`. We should probalby do some deduplication.

2020-11-18 21:42 UTC, notgne2 requested changes
All of these files need to be licensed, and given license headers using `reuse`

2020-11-18 21:42 UTC, notgne2 commented on .buildkite/pipeline.yml
> +      - nix-shell --run 'nix --experimental-features "nix-command flakes" flake check --impure'
What in this repo makes us have to use `--impure`?

2020-11-20 12:26 UTC, balsoft commented on flake.nix
> +    upload-daemon.url = "github:serokell/upload-daemon";
Likely not needed

2020-11-20 12:26 UTC, balsoft commented on flake.nix
> +    };
Likely not needed

2020-11-20 12:29 UTC, balsoft commented
Please don't put `common` in `servers`.

Also, I think it would be much cleaner to add a `profiles/website` directory and put `backups.nix` and `website.nix` there, export `nixosModules.website` and `nixosModules.backups` from the flake and then import `inputs.self.nixosModules.{website,backups}` from the servers that run the website.

2020-11-20 13:55 UTC, mkaito commented
I've moved common modules out to `lib/modules/`, and am passing the path to that via `specialArgs` instead of the flake. I don't think we should expose internal modules on the flake, and this is how `nixpkgs` does it with `modulesPath`.

2020-11-20 13:56 UTC, balsoft commented on flake.nix
> +          } // optionalAttrs (builtins.pathExists ./lib/modules) {
Is there a reason to do this here? If we factor this snippet out, we still have to specify `./lib/modules` in `flake.nix` of `-infra` repo

2020-11-20 14:00 UTC, mkaito commented on flake.nix
> +          } // optionalAttrs (builtins.pathExists ./lib/modules) {
Same problem as with `./servers` and `./common.nix`. Given the lack of lexical closures in nix, we'll have to pass those as arguments, unless you have a better idea.

2020-11-20 14:11 UTC, merged