Make sure our oauth2_proxy fork is used only for serokell-website
serokell/pegasus-infra pull request #5
Opened 2020-12-01 07:05 UTC by zhenyavinogradov

Our fork has known vulnerabilities (https://github.com/oauth2-proxy/oauth2-proxy/security/advisories/GHSA-5m6c-jp6f-2vcv), but we don't know if
serokell-website needs the features our fork implements or not, so we
cannot just switch it to the upstream module. But we know that we don't
the fork for any other service, so we should limit it to
serokell-website

Related issue: https://issues.serokell.io/issue/INT-158

2020-12-16 11:42 UTC, balsoft approved these changes
This is good, but maybe we should also patch our fork

2020-12-16 14:26 UTC, mkaito requested changes
Maybe move the package here instead of leaving it in serokell.nix

2020-12-17 08:06 UTC, zhenyavinogradov commented
I've moved the custom module to this repo

2021-01-13 17:13 UTC, mkaito approved these changes

2021-01-14 07:46 UTC, merged